# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
<<<<<<< HEAD
    - uses: actions/setup-node@v4
=======
      uses: actions/setup-node@v3
>>>>>>> f1234a48bd0b95ccaceb268ae35d26203620f645
      with:
        node-version: '20.x'
        cache: 'npm'
<<<<<<< HEAD
    - name: Install dependencies
    - run: rm -rf node_modules/
=======
>>>>>>> f1234a48bd0b95ccaceb268ae35d26203620f645
    - run: npm install
    - run: npm test
